apiVersion: v1
kind: Service
metadata:
  name: sample-app-service
  namespace : sample-app
spec:
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 80
    targetPort: 5000
  selector:
    component: sample-app-engine
  type: ClusterIP